# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: local
    hooks:
        # TODO: We can move generic hooks like this to a RH hook repo
        -   id: astyle
            name: astyle
            description: "Style files using astyle"
            entry: ./hooks/astyle.sh
            language: script

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
